var abschlussaufgabe_musicMemory;
(function (abschlussaufgabe_musicMemory) {
    class Musicbox {
        constructor(_colorStripes, _colorMusicbox) {
            this.x = 20;
            this.y = 20;
            this.colorStripes = "grey";
            this.colorMusicbox = "#D647CB";
            this.colorStripes = _colorStripes;
            this.colorMusicbox = _colorMusicbox;
        }
        update() {
            this.draw();
        }
        draw() {
            //Box
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "#000000";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "#FFE71B";
            abschlussaufgabe_musicMemory.crc2.rect(x, y, 50, 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            //Stripes
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x, y + 5);
            abschlussaufgabe_musicMemory.crc2.lineTo(90, y + 5);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x, y + 10);
            abschlussaufgabe_musicMemory.crc2.lineTo(90, y + 10);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x, y + 15);
            abschlussaufgabe_musicMemory.crc2.lineTo(90, y + 15);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x, y + 20);
            abschlussaufgabe_musicMemory.crc2.lineTo(90, y + 20);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x, y + 25);
            abschlussaufgabe_musicMemory.crc2.lineTo(90, y + 25);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x, y + 30);
            abschlussaufgabe_musicMemory.crc2.lineTo(90, y + 30);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x, y + 35);
            abschlussaufgabe_musicMemory.crc2.lineTo(90, y + 35);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x + 5, y);
            abschlussaufgabe_musicMemory.crc2.lineTo(x + 5, y + 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x + 10, y);
            abschlussaufgabe_musicMemory.crc2.lineTo(x + 10, y + 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x + 15, y);
            abschlussaufgabe_musicMemory.crc2.lineTo(x + 15, y + 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x + 20, y);
            abschlussaufgabe_musicMemory.crc2.lineTo(x + 20, y + 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x + 25, y);
            abschlussaufgabe_musicMemory.crc2.lineTo(x + 25, y + 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x + 30, y);
            abschlussaufgabe_musicMemory.crc2.lineTo(x + 30, y + 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x + 35, y);
            abschlussaufgabe_musicMemory.crc2.lineTo(x + 35, y + 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x + 40, y);
            abschlussaufgabe_musicMemory.crc2.lineTo(x + 40, y + 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            abschlussaufgabe_musicMemory.crc2.beginPath();
            abschlussaufgabe_musicMemory.crc2.strokeStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.fillStyle = "grey";
            abschlussaufgabe_musicMemory.crc2.moveTo(x + 45, y);
            abschlussaufgabe_musicMemory.crc2.lineTo(x + 45, y + 40);
            abschlussaufgabe_musicMemory.crc2.closePath();
            abschlussaufgabe_musicMemory.crc2.stroke();
            abschlussaufgabe_musicMemory.crc2.fill();
            //
        }
    }
    abschlussaufgabe_musicMemory.Musicbox = Musicbox;
})(abschlussaufgabe_musicMemory || (abschlussaufgabe_musicMemory = {}));
//# sourceMappingURL=musicbox.js.map